//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nissi.Repositorio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MAX-PC\\SQLEXPRESS;Initial Catalog=NISSI;User ID=amaximiano;Password=D" +
            "rica250479")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=nissi-server\\sqlexpress;Initial Catalog=NISSI;User ID=sa;Password=Nis" +
            "si@2009")]
>>>>>>> 0e7e752c875b412e16e75c56679cd0618d11db3e
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=max-pc\\sqlexpress;Initial Catalog=NISSI;User ID=sa;Password=Nissi@200" +
            "9")]
>>>>>>> local
        public string NissiDataBase {
            get {
                return ((string)(this["NissiDataBase"]));
            }
        }
    }
}
