//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nissi.WebPresentation.Administracao.Menu {
    
    
    public partial class Menu {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Nissi.WebPresentation.MasterPage Master {
            get {
                return ((Nissi.WebPresentation.MasterPage)(base.Master));
            }
        }
    }
}
